config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  namespace :admin do
    root :to => "posts#index"
    resources :posts, :tags, :composers, :categories, :comments, :users
  end

  get 'admin/auth' => 'admin/auth#index'
  post 'admin/auth' => 'admin/auth#create'
  get 'posts' => 'posts#index'
  get 'posts/read/:id' => 'posts#read'
  post  'posts/read/:id' => 'posts#comment'

  get 'auth/login' => 'auth#login'
  get 'auth/signup' => 'auth#signup'
  post 'auth/signup' => 'auth#create'
  post 'auth/login' => 'auth#signin'
  get 'auth/logout' => 'auth#logout'

  get 'forum' => 'thread#index'
  get 'forum/read/:id' => 'thread#read'
  get 'forum/create' => 'thread#create_form'
  post 'forum/create' => 'thread#create'
  post 'forum/read/:id' => 'thread#comment'

  get 'composers' => 'composers#index'
  get 'composers/read/:id' => 'composers#read'

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :post
  belongs_to :user

  def Comment.get_comments(id)
    Comment.left_joins(:post).left_joins(:user).select('users.name AS author, text, comments.created_at ').where(post_id: id)
  end
  def Comment.get_all_comments
    Comment.left_joins(:post).left_joins(:user).select('users.id AS author_id, posts.id AS post_id, comments.id AS comment_id ,users.name AS author, text, comments.created_at ')
  end
  def Comment.get_count(id)
    Comment.left_joins(:post).left_joins(:user).where(post_id: id).count
  end
end

app/models/composer.rb
class Composer < ApplicationRecord
  self.table_name = 'composers'
  validates :name, presence: true
  validates :date_of_birth, presence: true
  validates :description, presence: true

end

app/models/composition.rb
class Composition < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  self.table_name = 'thread_messages'
  validates :message, presence: true
  belongs_to :topic, class_name: 'Topic', foreign_key: 'thread_id'
  belongs_to :user

  def Message.get_with_join(id)
    Message.left_joins(:topic).left_joins(:user).select('users.name AS author, message, thread_messages.created_at ').where(thread_id: id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  self.table_name = 'posts'
  has_many :post_tags
  has_many :comments
  has_many :tags, :through => :post_tags
  validates :theme, presence: true
  validates :content, presence: true
  validates :bg_img, presence: true



  def self.search(search)
    if search
      self.where('theme LIKE :search', search: "%#{search}%")
    else
      self.all
    end
  end
  
  
  


end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  self.table_name = 'posts_tags'
  belongs_to :post
  belongs_to :tag
  def PostTag.get_with_join(id)
    PostTag.left_joins(:post).left_joins(:tag).select('tags.name as tag_name, tags.id as tag_id').where(post_id: id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  self.table_name = 'tags'
  has_many :post_tags
  has_many :posts, :through => :post_tags
  validates :name, presence: true
end

app/models/thread_category.rb
class ThreadCategory < ApplicationRecord
  self.table_name = 'thread_category'
  has_many :topics
  validates :name, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  self.table_name = 'threads'
  has_many :messages
  validates :title, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  belongs_to :user
  belongs_to :thread_category, class_name: 'ThreadCategory', foreign_key: 'category_id'
  def Topic.get_with_join(id)
    Topic.left_joins(:user).select("users.id as user_id, users.name AS 'author', title, description, threads.created_at, threads.id AS id").find(id)
  end

  def Topic.sanitized_order( column , direction = nil )
    direction ||= "DESC"

    raise "Column value of #{column} not permitted."       unless Topic.column_names.include?( column.to_s ) 
    raise "Direction value of #{direction} not permitted." unless [ "ASC", "DESC" ].include?( direction.to_s.upcase ) 

    self.order( "#{column} #{direction}" )
  end
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = 'users'
  has_secure_password
  validates :name, presence: true, on: :create
  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, presence: true, on: :create

  has_many :topics
  has_many :comments
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def login
    @user = User.new
  end
  
  def signin
    
    @user = User.find_by(email: params[:email])
    if !@user
      @error = "Не знайдено користувача із такого електронною поштою"
      return render :login
    end
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @error = "Невірний пароль"
      render :login
    end
  end

  def signup 
    @user = User.new
  end


  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to '/'
    else 
      render :signup
    end
  end

  def user_params
    params.permit(:email, :password, :name)
  end


  def logout
    session[:user_id] = nil
    redirect_to '/auth/login'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.select('id, theme, created_at, bg_img, content').limit(4).order(created_at: :desc)
    @latest_posts = @posts.map(&:attributes)
 
 
    @latest_posts.each do |post|
      post['comments'] = Comment.get_count(post['id'])
      post['tags'] = PostTag.get_with_join(post['id']).map(&:attributes)
    end
  end
end

app/controllers/thread_controller.rb
class ThreadController < ApplicationController
  before_action :authorized, only: [:create_form]

  TOPICS_PER_PAGE = 5

  def index
    @page = params.fetch(:page, 0).to_i
    condition = {}
    category = params.fetch(:category, nil)
    order_by = params.fetch(:order_by, :created_at)
    dir = params.fetch(:dir, :desc)
  
  
    @topics = Topic.left_joins(:user).left_joins(:thread_category)
                      .select("users.id as user_id, users.name AS 'author', title, description, threads.created_at as created_at, threads.id AS id, thread_category.name as category,thread_category.id as category_id")
                      .where(condition)
                      .offset(@page * TOPICS_PER_PAGE)
                      .limit(TOPICS_PER_PAGE)
                      .sanitized_order(order_by, dir)

                     
    @data = @topics.map(&:attributes)
    @total = Post.count
    @pages_count = @total / TOPICS_PER_PAGE
  end

  def read
    @topic = Topic.get_with_join(params[:id])
     @messages = Message.get_with_join(params[:id]).map(&:attributes)
    # @data = @topic.map(&:attributes)
  end

  def create
    params = topic_params
    params[:user_id] = session[:user_id]
    @topic = Topic.create(params)
    if @topic.valid?
      @topic.save
      redirect_to controller: 'thread', action: 'read', id: @topic.id
    else 
      @categories = ThreadCategory.all
      render :create_form
    end
  end

  def comment
    message = params.permit(:message)
    message[:user_id] = session[:user_id]
    message[:thread_id] = params[:id]
    @msg = Message.create(message)
    if @msg.valid?
      @msg.save
      redirect_back(fallback_location: '/')
    else 
      flash[:error] = @msg.errors.full_messages
      redirect_back(fallback_location: '/')
    end
  end

  def create_form
    @topic = Topic.new
    @categories = ThreadCategory.all
  end

  def topic_params
    params.permit(:title, :description, :category_id)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/thread_helper.rb
module ThreadHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/thread/create_form.html.erb
<div class="header-half">
<div class="h-100 header-text valign-wrapper header-wrapper">
  <div class="row">
    <div class="col s12">
      <a href="#!" class="breadcrumb">Головна</a>
      <a href="#!" class="breadcrumb">Створити тред</a>
    </div>
  </div>
</div>
</div>
<section class="auth-container">
<div class="container">
  <h5>Створити тред</h5>
  <div class="row">
  <%= form_tag(nil,{:class => 'col s12 l4'}) do %>
    <div class="auth-error col s12">
    <% if @topic.errors.full_messages.any? %>
      <% @topic.errors.full_messages.each do |error_message| %>
        <%= error_message  %> <br />
      <% end %>
    <% end %>
    </div>
        <div class="input-field col s12">
          <input id="title" name="title" type="text" />
          <label for="title">Тема</label>
        </div>
        <div class="input-field col s12">
        <select name="category_id">
          <option value="" disabled selected>Оберіть категорію</option>
          <% @categories.each do |category| %>
            <option value="<%=category['id']%>"><%=category['name']%></option>
          <% end %>

        </select>
        <label>Категорія</label>
      </div>
        <div class="input-field col s12">
          <textarea
            id="description"
            name="description"
            class="materialize-textarea has-character-counter"
            data-length="500"
          ></textarea>
          <label for="description">Опис</label>
        </div>
        <div class="col s12">
          <button class="waves-effect waves-light btn-small" type="submit">
            Опублікувати
          </button>
        </div>
      <% end %>
  </div>
</div>
</section>

app/views/thread/index.html.erb
<div class="header-half">
<div class="h-100 header-text valign-wrapper header-wrapper">
  <div class="row">
    <div class="col s12">
      <a href="#!" class="breadcrumb">Головна</a>
      <a href="#!" class="breadcrumb">Форум</a>
    </div>
  </div>
</div>
</div>
<section class="container">
<div class="row">
<div class="input-field col l4 s12">
    <select onchange="location = this.value;">
      <option value="" disabled selected>Обрати сортування</option>
      <option value="<%= forum_path(order_by: :created_at, dir: :desc) %>">Новіші</option>
      <option value="<%= forum_path(order_by: :created_at, dir: :asc) %>">Старіші</option>

    </select>
    <label>Сортувати за</label>
  </div>
  <div class="col l9 s12">
    <div class="sec card-bg">
      <div class="sec-content">
      <% @data.each do |topic| %>
        <div class="category">
        
          <div class="category-icon">
            <span class="icon"
              ><i class="tiny material-icons">mode_comment</i></span
            >
          </div>
          <div class="category-info">
            <div class="category-detail">
              <a href="/forum/read/<%= topic['id'] %>"><%= topic['title'] %></a>
              <div class="category-desc"><%= topic['description'].truncate(110) %></div>
            </div>
            <div class="category-stat">
            <% if topic['category'] %>

              <div><%= link_to topic['category'], forum_path(category: topic['category_id']) %></div>
              <% end %>
            </div>
            <div class="category-meta">
  
              <div>by <span class="author"><%= topic['author'] %></span></div>
              <div><%= topic['created_at'].to_time.to_formatted_s(:short)   %></div>
            </div>
          </div>
        </div>
        <% end %>
    
          <ul class="pagination">
            <% if  @page >= 1 %>
              <li class="waves-effect">
                <%= link_to forum_path(params.permit(:dir, :order_by).merge(page: @page - 1)) do %>
                  <i class="material-icons">chevron_left</i>
                <% end %>
              </li>
            <% end %>
          
            <% for i in 0..@pages_count   %>
              <li class="waves-effect <%= @page == i ? 'active' :''  %>">
                <%= link_to i + 1, forum_path(params.permit(:dir, :order_by).merge(page: i)) %>
              </li>
            <% end %>

            <% if @pages_count  > @page %>
              <li class="waves-effect">
                <%= link_to forum_path(params.permit(:dir, :order_by).merge(page: @page + 1)) do %>
                  <i class="material-icons">chevron_right</i>
                <% end %>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
    
  </div>
  <div class="col l3 s12">
    <div class="card-panel card-bg">
      <h5 class="sidebar-title">Recent Topics</h5>
      <ul>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
      </ul>
    </div>
  </div>
</div>
</section>

app/views/thread/read.html.erb
<div class="header-half">
<div class="h-100 header-text valign-wrapper header-wrapper">
  <div class="row">
    <div class="col s12">
      <a href="/" class="breadcrumb">Головна</a>
      <a href="/forum" class="breadcrumb">Форум</a>
      <a href="#" class="breadcrumb"><%= @topic['title'] %></a>
    </div>
  </div>
</div>
</div>
<section class="container single-topic">
<div class="row">
  <div class="col l9 s12">
    <div class="row">
      <div class="col l1">
        <div class="author"><%= @topic['author'] %></div>
      </div>
      <div class="col l11">
        <div class="topic card-bg">
          <h5 class="topic-header"><%= @topic['title'] %> </h5>
          <p>
          <%= @topic['description'] %>
          </p>
          <div class="topic-footer">
            <div><%= @topic['created_at'].to_time.to_formatted_s(:long)   %></div>
          </div>
        </div>
      </div>
    </div>
    <% @messages.each do |msg| %>
    <div class="row">
      <div class="col l1">
        <div class="author"><%= msg['author']%></div>
      </div>
      <div class="col l11">
        <div class="topic card-bg">
          <p>
          <%= msg['message']%>
          </p>
          <div class="topic-footer">
            <div><%= msg['created_at'].to_time.to_formatted_s(:long)   %></div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div class="comment-form col l9 s12">
      <h5 class="form-title">
        Надіслати повідомлення
      </h5>
      <% if logged_in? %>
      <%= form_tag do %>
        <div class="auth-error col s12">
          <% if flash[:error] && flash[:error].any? %>
            <% flash[:error].each do |error_message| %>
              <%= error_message  %> <br />
            <% end %>
          <% end %>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <textarea
              id="message"
              class="materialize-textarea has-character-counter"
              data-length="500"
              name="message"
              required
            ></textarea>
            <label for="textarea1">Повідомлення</label>
          </div>
        </div>
        <button
          type="submit"
          class="waves-effect waves-light btn comment-form-btn"
        >
          Надіслати
        </button>
        <% end %>
        <% end %>
    </div>
  </div>

  <div class="col l3 s12">
    <div class="card-panel card-bg">
      <h5 class="sidebar-title">Recent Topics</h5>
      <ul>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
        <li><a href="#" class="sidebar-link">Lorem, ipsum.</a></li>
      </ul>
    </div>
  </div>
</div>
</section>