config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  namespace :admin do
    root :to => "posts#index"
    resources :posts, :tags, :composers, :categories, :comments, :users
  end

  get 'admin/auth' => 'admin/auth#index'
  post 'admin/auth' => 'admin/auth#create'
  get 'posts' => 'posts#index'
  get 'posts/read/:id' => 'posts#read'
  post  'posts/read/:id' => 'posts#comment'

  get 'auth/login' => 'auth#login'
  get 'auth/signup' => 'auth#signup'
  post 'auth/signup' => 'auth#create'
  post 'auth/login' => 'auth#signin'
  get 'auth/logout' => 'auth#logout'

  get 'forum' => 'thread#index'
  get 'forum/read/:id' => 'thread#read'
  get 'forum/create' => 'thread#create_form'
  post 'forum/create' => 'thread#create'
  post 'forum/read/:id' => 'thread#comment'

  get 'composers' => 'composers#index'
  get 'composers/read/:id' => 'composers#read'

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :post
  belongs_to :user

  def Comment.get_comments(id)
    Comment.left_joins(:post).left_joins(:user).select('users.name AS author, text, comments.created_at ').where(post_id: id)
  end
  def Comment.get_all_comments
    Comment.left_joins(:post).left_joins(:user).select('users.id AS author_id, posts.id AS post_id, comments.id AS comment_id ,users.name AS author, text, comments.created_at ')
  end
  def Comment.get_count(id)
    Comment.left_joins(:post).left_joins(:user).where(post_id: id).count
  end
end

app/models/composer.rb
class Composer < ApplicationRecord
  self.table_name = 'composers'
  validates :name, presence: true
  validates :date_of_birth, presence: true
  validates :description, presence: true

end

app/models/composition.rb
class Composition < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  self.table_name = 'thread_messages'
  validates :message, presence: true
  belongs_to :topic, class_name: 'Topic', foreign_key: 'thread_id'
  belongs_to :user

  def Message.get_with_join(id)
    Message.left_joins(:topic).left_joins(:user).select('users.name AS author, message, thread_messages.created_at ').where(thread_id: id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  self.table_name = 'posts'
  has_many :post_tags
  has_many :comments
  has_many :tags, :through => :post_tags
  validates :theme, presence: true
  validates :content, presence: true
  validates :bg_img, presence: true



  def self.search(search)
    if search
      self.where('theme LIKE :search', search: "%#{search}%")
    else
      self.all
    end
  end
  
  
  


end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  self.table_name = 'posts_tags'
  belongs_to :post
  belongs_to :tag
  def PostTag.get_with_join(id)
    PostTag.left_joins(:post).left_joins(:tag).select('tags.name as tag_name, tags.id as tag_id').where(post_id: id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  self.table_name = 'tags'
  has_many :post_tags
  has_many :posts, :through => :post_tags
  validates :name, presence: true
end

app/models/thread_category.rb
class ThreadCategory < ApplicationRecord
  self.table_name = 'thread_category'
  has_many :topics
  validates :name, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  self.table_name = 'threads'
  has_many :messages
  validates :title, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  belongs_to :user
  belongs_to :thread_category, class_name: 'ThreadCategory', foreign_key: 'category_id'
  def Topic.get_with_join(id)
    Topic.left_joins(:user).select("users.id as user_id, users.name AS 'author', title, description, threads.created_at, threads.id AS id").find(id)
  end

  def Topic.sanitized_order( column , direction = nil )
    direction ||= "DESC"

    raise "Column value of #{column} not permitted."       unless Topic.column_names.include?( column.to_s ) 
    raise "Direction value of #{direction} not permitted." unless [ "ASC", "DESC" ].include?( direction.to_s.upcase ) 

    self.order( "#{column} #{direction}" )
  end
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = 'users'
  has_secure_password
  validates :name, presence: true, on: :create
  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, presence: true, on: :create

  has_many :topics
  has_many :comments
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def login
    @user = User.new
  end
  
  def signin
    
    @user = User.find_by(email: params[:email])
    if !@user
      @error = "Не знайдено користувача із такого електронною поштою"
      return render :login
    end
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @error = "Невірний пароль"
      render :login
    end
  end

  def signup 
    @user = User.new
  end


  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to '/'
    else 
      render :signup
    end
  end

  def user_params
    params.permit(:email, :password, :name)
  end


  def logout
    session[:user_id] = nil
    redirect_to '/auth/login'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/thread_helper.rb
module ThreadHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicworld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
    href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet"
    />
    <%= stylesheet_link_tag 'admin' %>
    <%= javascript_pack_tag 'admin' %>
    
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  </head>

  <body>
    <% if is_admin? %>
      <ul id="slide-out" class="sidenav sidenav-fixed">
        <li><%= link_to "<i class='material-icons'>receipt</i>Пости".html_safe, admin_posts_path %></li>
        <li><%= link_to "<i class='material-icons'>queue</i>Створити пост".html_safe, new_admin_post_path %></li>
        <li><%= link_to "<i class='material-icons'>label</i>Теги".html_safe, admin_tags_path %></li>
        <li><%= link_to "<i class='material-icons'>add</i>Додати тег".html_safe, new_admin_tag_path %></li>
        <li><%= link_to "<i class='material-icons'>music_note</i>Композитори".html_safe, admin_composers_path %></li>
        <li><%= link_to "<i class='material-icons'>add_circle_outline</i>Додати композитора".html_safe, new_admin_composer_path %></li>
        <li><%= link_to "<i class='material-icons'>list</i>Список категорій".html_safe, admin_categories_path %></li>
         <li><%= link_to "<i class='material-icons'>playlist_add</i>Додати Категорію".html_safe, new_admin_category_path %></li>
         <li><%= link_to "<i class='material-icons'>mode_comment</i>Коментарі".html_safe, admin_comments_path %></li>
         <li><%= link_to "<i class='material-icons'>assignment_ind</i>Користувачі".html_safe, admin_users_path %></li>
      </ul>
      <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <% end %>

    
    <main>
      <%= yield %>
    </main>
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="https://unpkg.com/vanilla-datatables@latest/dist/vanilla-dataTables.min.js" type="text/javascript"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicworld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
    href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet"
    />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
      <nav class="">
        <div class="nav-wrapper container">
          <a href="/" class="brand-logo">Musicworld</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"
            ><i class="material-icons">menu</i></a
          >
          <ul
            id="nav-mobile"
            data-target="mobile-demo"
            class="right hide-on-med-and-down"
          >
            <li><%= link_to "Форум", "/forum" %></li>
            <li><%= link_to "Новини", "/posts" %></li>
            <li><%= link_to "Композитори", "/composers" %></li>
            <% if logged_in? %>
              <li><%= link_to "Вихід", "/auth/logout" %></li>
            <% else %>
              <li><%= link_to "Авторизація", "/auth/login" %></li>
              <li><%= link_to "Реєстрація", "/auth/signup" %></li>
            <% end %>
            
            <li><%= link_to "Створити тред", "/forum/create" %></li>
          </ul>
        </div>
      </nav>
      <ul class="sidenav" id="mobile-demo">
      <li><a href="forum.html">Forum</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a href="collapsible.html">Javascript</a></li>
      <li><a href="mobile.html">Mobile</a></li>
    </ul>
    <%= yield %>
    <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col l4 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">
            You can use rows and columns here to organize your footer content.
          </p>
        </div>
        <div class="col l4 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>

      <div class="row footer-stats">
        <div class="col l3 s6 stat">
          <b>Total Posts</b>
          <b>3</b>
        </div>
        <div class="col l3 s6 stat">
          <b>Total Posts</b>
          <b>3</b>
        </div>
        <div class="col l3 s6 stat">
          <b>Total Posts</b>
          <b>3</b>
        </div>
        <div class="col l3 s6 stat">
          <b>Total Posts</b>
          <b>3</b>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>